"""empty message

Revision ID: 3a4f78721891
Revises: 067b6ab9fcaf
Create Date: 2020-08-15 02:07:39.207580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4f78721891'
down_revision = '067b6ab9fcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'complite')
    # ### end Alembic commands ###
